baseURL = "https://sportchallengetraining.fr/"
languageCode = "fr-FR"
title = "Sport Challenge Training"
theme = "flavor"
defaultContentLanguage = "fr"
enableRobotsTXT = true
enableGitInfo = false
paginate = 9
summaryLength = 70

[params]
  tagline = "Performance, Bien-être et Dépassement de soi"
  description = "Ressources et conseils d'experts pour optimiser votre entraînement, nutrition et récupération. Atteignez vos objectifs sportifs avec des méthodes éprouvées."
  author = "SCT